* Installation de mariadb dans Termux
** Installer Termux et termux-api

   https://termux.com

   #+BEGIN_SRC shell
     pkg install termux-api
   #+END_SRC
** Partager des fichiers dans Termux
   https://wiki.termux.com/wiki/Sharing_Data


** Afficher le clavier s'il a disparu
   Il y a un tiroir à gauche de l'écran que l'on peut afficher en le faisant glisser vers la droite.
   Dans le tiroir =Keyboard= permet d'afficher le clavier.
** Quitter une session Termux
   - Maintenir un appui sur l'écran.
   - More...
   - Kill process

** Installation de mariadb dans Termux
   In your Termux application execute:

   #+BEGIN_SRC shell
     apt update
   #+END_SRC

   And then:

   #+BEGIN_SRC shell
     apt upgrade
     pkg install mariadb
   #+END_SRC

  
   The command shown above will also initialize the database with 2 all-privilege accounts.
   The first one is "root" which is inaccessible and the second one with name of your Termux user (check with command =id -un= or =whoami=).


* Start the MySQL daemon 
  (this should also be done if we restart the phone).

  To do this, execute:

  #+BEGIN_SRC shell
    mysqld_safe -u root &
  #+END_SRC

  What we do is run =mysqld_safe= with the root user; the ampersand =&= is to run it in the background.
  Run it _and press Enter_. 


* Stop MySQL/MariaDB process
  If you want to stop the process, find the ID from whichever process that has the word “mysql” using ps with grep, and then kill them with kill -9 [ID], the -9 is to send a KILL SIGNAL.

  #+BEGIN_SRC shell
    ps aux | grep mysql
  #+END_SRC

  If you take a  look, they are two processes with 15406 and 15488 ids. The third is from grep but we omit it. Remember that it will change in your case because the process id isn’t always the same.

  When you have the IDs kill them:
  #+BEGIN_SRC shell
    kill -9 15406
    kill -9 15488
  #+END_SRC

  Or restart the phone


* Enable access to root account
  To enable access to root account, you need to login with your Termux user name

  #+BEGIN_SRC shell
    mysql -u $(whoami)
  #+END_SRC

  and manually change password for root

  #+BEGIN_SRC shell
    use mysql;
    set password for 'root'@'localhost' = password('YOUR_ROOT_PASSWORD_HERE');
    flush privileges;
    quit
  #+END_SRC

* Login
** Now y can login as 'root'

   Verify that you are able to login as 'root' with:
   #+BEGIN_SRC sql
     mysql -u root -p
   #+END_SRC

   You will need to provide password set in previous step. (hatterer)

** Users
   Il y a trois types d'utilisateur d'un SGBD, trois rôles bien distincts :
   1. l'administrateur du SGBD (DataBases Administrator -DBA) et donc des Bases de Données. Son rôle est d'installer et gérer le SGBD dans sa globalité. Pour MySQL ou MariaDB, il s'appelle 'root'.
   2. les créateurs de Bases de Données dans un SGBD existant : création (CREATE TABLE), modification (ALTER TABLE), suppression (DROP TABLE) de tables...
   3. les utilisateurs de bases de données.

   Il ne faut pas travailler sur une bases de données en tant qu'administrateur de bases de données, ce n'est pas son rôle.
   L'administrateur crée une base de données et délègue sa gestion à un autre utilisateur.

* Commandes de base en ligne de commande
  - =SHOW DATABASES=
  Liste les bases de données
  - =SHOW STATUS=
  Affiche le statut du serveur
  - =USE nom_base=
  Sélectionne la base par défaut
  - =SHOW TABLES=
  Affiche les tables de la base courante
  - =DESCRIBLE table=
  Affiche la structure de la table
  - =SELECT * FROM table=
  Affiche le contenu de la table
  - =CREATE DATABASE base=
  Crée une nouvelle base de données


* Initialiser  
** Création d'une nouvelle base de données 
   Création d'une nouvelle base de données vierge =bd_gestion_des_notes=
   #+BEGIN_SRC sql
     root: CREATE DATABASE bd_gestion_des_notes;
     root: SHOW DATABASES;
   #+END_SRC

** CREATION d'un utilisateur 'gestionnaire'
   Utilisateur pouvant créer ou modifier des tables dans la base de données =bd_gestion_des_notes=
   #+BEGIN_SRC sql
     root: CREATE USER 'user_gestionnaire'@'localhost' IDENTIFIED BY 'gestionnaire';
     root: GRANT ALL PRIVILEGES ON bd_gestion_des_notes.* TO 'user_gestionnaire'@'localhost';
     root: quit
   #+END_SRC		
** Se connecter en tant que gestionnaire:
   #+BEGIN_SRC sql
     mysql -u user_gestionnaire -p
     use bd_gestion_des_notes;      
   #+END_SRC

* How to do MySQL “show users"

  To begin, you need to make sure you have MySQL server properly installed and running. Then you need to login as an administrative users via the mysql> prompt 

  Once logged in, run the following command on the mysql> prompt:

  #+BEGIN_SRC shell
    select host, user from mysql.user;
  #+END_SRC

* sql-mode dans emacs
** se connecter au serveur dans emacs
   'M-x sql-mysql'

   - en root
     Renseigner:
     - User: root
     - Password: hatterer
     - Database : bd_gestion_des_notes
     - Server: localhost
   - en gestionnaire
     Renseigner:
     - User: user_gestionnaire
     - Password: gestionnaire
     - Database : bd_gestion_des_notes
     - Server: localhost

** Connexion facilitée 
   À placer dans .emacs.d/init.el
   #+BEGIN_SRC elisp
     (setq sql-user "user_gestionnaire")
     (setq sql-password "gestionnaire")
     (setq sql-database "bd_gestion_des_notes")
     (setq sql-server "localhost")
   #+END_SRC


** SQL-UPCASE
   https://www.emacswiki.org/emacs/SqlUpcase
   A minor mode which converts lower-case SQL keywords to upper-case as you type or otherwise insert text in the buffer – for instance, killing and yanking an entire SQL query would upcase all keywords in that query.
   Commands are also provided for upcasing all keywords in the buffer (‘sql-upcase-buffer’), or a specified region (‘sql-upcase-region’).
   #+BEGIN_SRC elisp
     (when (require 'sql-upcase nil :noerror)
       (add-hook 'sql-mode-hook 'sql-upcase-mode)
       (add-hook 'sql-interactive-mode-hook 'sql-upcase-mode))
   #+END_SRC


* How to run sql script
  If you’re at the MySQL command line mysql> you have to declare the SQL file as source.

  #+BEGIN_SRC sql
    mysql> source \home\user\Desktop\script_file.sql;
  #+END_SRC



